# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ithil < Formula
  desc "A Terminal User Interface (TUI) Telegram client built with Go and Bubbletea"
  homepage "https://github.com/lvcasx1/ithil"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lvcasx1/ithil/releases/download/v0.1.5/ithil_0.1.5_Darwin_x86_64.tar.gz"
      sha256 "eeb427118b67001f1920a5aafc1351fe1f92f4ee9fb3e9582224e2fa42bb8b94"

      def install
        bin.install "ithil"
        (etc/"ithil").install "config.example.yaml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lvcasx1/ithil/releases/download/v0.1.5/ithil_0.1.5_Darwin_arm64.tar.gz"
      sha256 "c74769bb67a8fb08b6abfaf56a8b24f8682c30cd1535f1df7d39876e110d988a"

      def install
        bin.install "ithil"
        (etc/"ithil").install "config.example.yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lvcasx1/ithil/releases/download/v0.1.5/ithil_0.1.5_Linux_x86_64.tar.gz"
      sha256 "8f595e0cce40128fa4dce5da01e025958f1b22ece57ab03dfedbec941514b356"
      def install
        bin.install "ithil"
        (etc/"ithil").install "config.example.yaml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lvcasx1/ithil/releases/download/v0.1.5/ithil_0.1.5_Linux_arm64.tar.gz"
      sha256 "604390f83da3017e51e3739fb41c9f087190372cc9cc4d7a07f6707e33d44b83"
      def install
        bin.install "ithil"
        (etc/"ithil").install "config.example.yaml"
      end
    end
  end

  def caveats
    <<~EOS
      To get started, copy the example configuration:
        cp #{etc}/ithil/config.example.yaml ~/.config/ithil/config.yaml

      Then edit the configuration file with your Telegram API credentials from https://my.telegram.org
    EOS
  end

  test do
    system "#{bin}/ithil", "-version"
  end
end
