# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ithil < Formula
  desc "A Terminal User Interface (TUI) Telegram client built with Go and Bubbletea"
  homepage "https://github.com/lvcasx1/ithil"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lvcasx1/ithil/releases/download/v0.1.1/ithil_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "6ddc62bf7007dd9d3d3c55867cba59f757dc760734304977e7c3397081b6a241"

      def install
        bin.install "ithil"
        (etc/"ithil").install "config.example.yaml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lvcasx1/ithil/releases/download/v0.1.1/ithil_0.1.1_Darwin_arm64.tar.gz"
      sha256 "1554a3ed263ab0034cee686b70bd51a9ebec98aa302852b9be61d32e50713c0e"

      def install
        bin.install "ithil"
        (etc/"ithil").install "config.example.yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lvcasx1/ithil/releases/download/v0.1.1/ithil_0.1.1_Linux_x86_64.tar.gz"
      sha256 "8d3a2f28ec0ee5a59acf0f36ffd6bbd55d496682176fed385efca7f5657cce9e"
      def install
        bin.install "ithil"
        (etc/"ithil").install "config.example.yaml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lvcasx1/ithil/releases/download/v0.1.1/ithil_0.1.1_Linux_arm64.tar.gz"
      sha256 "f72078c03b9b0f7ca95c48bca299290e2f7f79e9d041d2de23da29fa9f075187"
      def install
        bin.install "ithil"
        (etc/"ithil").install "config.example.yaml"
      end
    end
  end

  def caveats
    <<~EOS
      To get started, copy the example configuration:
        cp #{etc}/ithil/config.example.yaml ~/.config/ithil/config.yaml

      Then edit the configuration file with your Telegram API credentials from https://my.telegram.org
    EOS
  end

  test do
    system "#{bin}/ithil", "-version"
  end
end
