# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ithil < Formula
  desc "A Terminal User Interface (TUI) Telegram client built with Go and Bubbletea"
  homepage "https://github.com/lvcasx1/ithil"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lvcasx1/ithil/releases/download/v0.1.6/ithil_0.1.6_Darwin_x86_64.tar.gz"
      sha256 "42e29fe047cdce6a1071b2db5a77ceeaac800f5eca4e454be8cda1aa07709234"

      def install
        bin.install "ithil"
        (etc/"ithil").install "config.example.yaml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lvcasx1/ithil/releases/download/v0.1.6/ithil_0.1.6_Darwin_arm64.tar.gz"
      sha256 "196257f709956c7a66ca4ad631e298ae1e0eac894f1cd912968ea09a9312207f"

      def install
        bin.install "ithil"
        (etc/"ithil").install "config.example.yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lvcasx1/ithil/releases/download/v0.1.6/ithil_0.1.6_Linux_x86_64.tar.gz"
      sha256 "c2397a74988b3f412bdb39517a2a86b472b400de7526edbf7e9163070f39254d"
      def install
        bin.install "ithil"
        (etc/"ithil").install "config.example.yaml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lvcasx1/ithil/releases/download/v0.1.6/ithil_0.1.6_Linux_arm64.tar.gz"
      sha256 "23090f59be3a37245d2151320a36a23b8b0bcf689bc7c71ad86dbf4e394c3974"
      def install
        bin.install "ithil"
        (etc/"ithil").install "config.example.yaml"
      end
    end
  end

  def caveats
    <<~EOS
      To get started, copy the example configuration:
        cp #{etc}/ithil/config.example.yaml ~/.config/ithil/config.yaml

      Then edit the configuration file with your Telegram API credentials from https://my.telegram.org
    EOS
  end

  test do
    system "#{bin}/ithil", "-version"
  end
end
