# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quikgit < Formula
  desc "A GitHub repository manager with terminal user interface (TUI)"
  homepage "https://github.com/lvcasx1/quikgit"
  version "1.0.4"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lvcasx1/quikgit/releases/download/v1.0.4/quikgit_1.0.4_Darwin_x86_64.tar.gz"
      sha256 "765cae17063226c3c85ad982a9c9999b81b2325fddc4e01fceb2e304aa1a5645"

      def install
        bin.install "quikgit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lvcasx1/quikgit/releases/download/v1.0.4/quikgit_1.0.4_Darwin_arm64.tar.gz"
      sha256 "13f2b5a0df74f25de19f9f33eb9a5f19f1c063e1358b10becb6963dc357553f1"

      def install
        bin.install "quikgit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lvcasx1/quikgit/releases/download/v1.0.4/quikgit_1.0.4_Linux_x86_64.tar.gz"
      sha256 "3335c55bc285ac54cf9f0999ec2cbf540bfb474fbc5f1699bb848cf741459e09"
      def install
        bin.install "quikgit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lvcasx1/quikgit/releases/download/v1.0.4/quikgit_1.0.4_Linux_arm64.tar.gz"
      sha256 "e6ad906970e7ba3f581cab88a84b8c14822344c99037be698da885cc5ec85f7b"
      def install
        bin.install "quikgit"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with QuikGit:

        1. Authenticate with GitHub:
           quikgit

        2. For QR code authentication, set up GitHub OAuth App:
           See: https://github.com/lvcasx1/quikgit/blob/main/AUTHENTICATION_SETUP.md

        3. Alternatively, use a personal access token via environment variable:
           export GITHUB_TOKEN=your_token_here
    EOS
  end

  test do
    system "#{bin}/quikgit", "--version"
  end
end
