# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quikgit < Formula
  desc "A GitHub repository manager with terminal user interface (TUI)"
  homepage "https://github.com/lvcasx1/quikgit"
  version "1.0.5"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lvcasx1/quikgit/releases/download/v1.0.5/quikgit_1.0.5_Darwin_x86_64.tar.gz"
      sha256 "5b10a64f9ade3633e6918555f4715c47dc0a23bf01f9ac9715833a4ecd632d90"

      def install
        bin.install "quikgit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lvcasx1/quikgit/releases/download/v1.0.5/quikgit_1.0.5_Darwin_arm64.tar.gz"
      sha256 "a10aa9c734a8d336f747090a4e4c8e73a78da147b82f57404cbae188003fab32"

      def install
        bin.install "quikgit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lvcasx1/quikgit/releases/download/v1.0.5/quikgit_1.0.5_Linux_x86_64.tar.gz"
      sha256 "ee71d496542a8f76aa10e72d40bd292100b198a9bd2d18e303df0742e7059c47"
      def install
        bin.install "quikgit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lvcasx1/quikgit/releases/download/v1.0.5/quikgit_1.0.5_Linux_arm64.tar.gz"
      sha256 "e4e707669a64719feda7a840cc540bd3acd63eaaead80b958d216916ea00fb8e"
      def install
        bin.install "quikgit"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with QuikGit:

        1. Authenticate with GitHub:
           quikgit

        2. For QR code authentication, set up GitHub OAuth App:
           See: https://github.com/lvcasx1/quikgit/blob/main/AUTHENTICATION_SETUP.md

        3. Alternatively, use a personal access token via environment variable:
           export GITHUB_TOKEN=your_token_here
    EOS
  end

  test do
    system "#{bin}/quikgit", "--version"
  end
end
