# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quikgit < Formula
  desc "A GitHub repository manager with terminal user interface (TUI)"
  homepage "https://github.com/lvcasx1/quikgit"
  version "1.0.6"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lvcasx1/quikgit/releases/download/v1.0.6/quikgit_1.0.6_Darwin_x86_64.tar.gz"
      sha256 "61cc460bc35f43a89a826b1d9789e8341ffe841bab905ae15c7af7db2798946b"

      def install
        bin.install "quikgit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lvcasx1/quikgit/releases/download/v1.0.6/quikgit_1.0.6_Darwin_arm64.tar.gz"
      sha256 "5be5a8026a31a57409b5f6d35bb16f13f116814239f3d0698660f21978ce19fd"

      def install
        bin.install "quikgit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lvcasx1/quikgit/releases/download/v1.0.6/quikgit_1.0.6_Linux_x86_64.tar.gz"
      sha256 "df9d129feacde74be623d633e395ee0a44fdd2b39d5f3212e5abc96cf50470ec"
      def install
        bin.install "quikgit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lvcasx1/quikgit/releases/download/v1.0.6/quikgit_1.0.6_Linux_arm64.tar.gz"
      sha256 "839c0cf6d90ff3644120c813654365dce52ee3362233e0d8ada7cdce7b148876"
      def install
        bin.install "quikgit"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with QuikGit:

        1. Authenticate with GitHub:
           quikgit

        2. For QR code authentication, set up GitHub OAuth App:
           See: https://github.com/lvcasx1/quikgit/blob/main/AUTHENTICATION_SETUP.md

        3. Alternatively, use a personal access token via environment variable:
           export GITHUB_TOKEN=your_token_here
    EOS
  end

  test do
    system "#{bin}/quikgit", "--version"
  end
end
